#!/usr/bin/env pwsh
# Initialize .learning-profile directory for study.skill
# Usage: .\init-profile.ps1 [-Path <path>] (default: ~/learning)

param(
    [string]$Path = "$env:USERPROFILE\learning"
)

$profileDir = "$Path\.learning-profile"
$profileFile = "$profileDir\profile.json"
$coursesDir = "$profileDir\courses"

New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
New-Item -ItemType Directory -Force -Path $coursesDir | Out-Null
New-Item -ItemType Directory -Force -Path "$Path\courses" | Out-Null
$created = @()

# profile.json
if (-not (Test-Path -LiteralPath $profileFile)) {
    $now = (Get-Date).ToString("yyyy-MM-ddTHH:mm:sszzz")
    @"
{
  "schema_version": 1,
  "learner_id": "default",
  "created_at": "$now",
  "updated_at": "$now",
  "preferences": {
    "native_language": "zh",
    "daily_time_budget_minutes": 30,
    "feedback_style": "normal",
    "correction_mode": "inline"
  }
}
"@ | Set-Content -LiteralPath $profileFile -Encoding UTF8
    $created += "profile.json"
} else {
    Write-Host "  profile.json already exists — skipped"
}

# AGENTS.md hint
$agentsFile = "$Path\AGENTS.md"
$hintMarker = "# [study.skill] review-check"
$agentsContent = if (Test-Path $agentsFile) { Get-Content $agentsFile -Raw } else { "" }
if ($agentsContent -and $agentsContent.Contains($hintMarker)) {
    Write-Host "  AGENTS.md review hint already present — skipped"
} else {
    @'

# [study.skill] review-check
# The following instructions are auto-generated by study.skill init script.

## 学习助手
如果你的工作目录下存在 `.learning-profile/` 目录，在每次会话开始时：
1. 运行 `python .learning-profile/scripts/check-reviews.py`（如果当前环境只有 `python3`，则用 `python3`）。
2. 如果脚本输出到期复习项，第一句话提醒用户：
   "你有 {n} 个知识点需要复习：{list}。先花几分钟回顾一下？"
3. 如果脚本没有输出，不主动提及复习。
'@ | Add-Content -LiteralPath $agentsFile -Encoding UTF8
    $created += "AGENTS.md review hint (appended)"
}

# Always copy runtime helper scripts to profile (used by all platforms)
$profileScripts = "$profileDir\scripts"
New-Item -ItemType Directory -Force -Path $profileScripts | Out-Null
foreach ($scriptName in @("check-reviews.py", "record-review.py", "write-state.py")) {
    $repoScript = Join-Path $PSScriptRoot $scriptName
    Copy-Item $repoScript (Join-Path $profileScripts $scriptName) -Force
    $created += "scripts\$scriptName"
}

# Claude Code-specific: SessionStart hook config
$claudeDir = "$Path\.claude"
if (Test-Path $claudeDir) {
    Write-Host "  Claude Code detected. See references/automation/claude-code.md for hook setup."
} else {
    Write-Host "  No .claude/ directory — skipping Claude Code hook setup"
}

if ($created.Count -gt 0) {
    Write-Host "Learning profile initialized at $Path"
    foreach ($f in $created) { Write-Host "  created: $f" }
} else {
    Write-Host "Learning profile already exists at $Path (no files created)"
}
Write-Host "  courses\"
