#!/usr/bin/env bash
# Initialize .learning-profile directory for study.skill
# Usage: ./init-profile.sh [path] (default: ~/learning)

LEARNING_DIR="${1:-$HOME/learning}"
PROFILE_DIR="$LEARNING_DIR/.learning-profile"
PROFILE_FILE="$PROFILE_DIR/profile.json"
COURSES_DIR="$PROFILE_DIR/courses"

mkdir -p "$PROFILE_DIR"
mkdir -p "$COURSES_DIR"
mkdir -p "$LEARNING_DIR/courses"
CREATED=()

# profile.json — global learner preferences
if [ ! -f "$PROFILE_FILE" ]; then
    cat > "$PROFILE_FILE" << EOF
{
  "schema_version": 2,
  "learner_id": "default",
  "created_at": "$(date -Iseconds)",
  "updated_at": "$(date -Iseconds)",
  "preferences": {
    "native_language": "zh",
    "daily_time_budget_minutes": 30,
    "feedback_style": "normal",
    "correction_mode": "inline",
    "automation_declined": false,
    "automation_declined_at": null
  },
  "learner_profile": {
    "baseline": null,
    "goals": [],
    "known_languages": [],
    "weak_prereqs": [],
    "analogy_preferences": [],
    "teaching_constraints": [],
    "materials_summary": null,
    "updated_at": null
  }
}
EOF
    CREATED+=("profile.json")
else
    echo "  profile.json already exists — skipped"
fi

# AGENTS.md hint — universal session-start hook
AGENTS_FILE="$LEARNING_DIR/AGENTS.md"
HINT_MARKER="# [study.skill] review-check"
if [ -f "$AGENTS_FILE" ] && grep -q "$HINT_MARKER" "$AGENTS_FILE" 2>/dev/null; then
    echo "  AGENTS.md review hint already present — skipped"
else
    cat >> "$AGENTS_FILE" << 'EOF'

# [study.skill] review-check
# The following instructions are auto-generated by study.skill init script.
# They tell the agent to check for overdue reviews on every session start.

## 学习助手
如果你的工作目录下存在 `.learning-profile/` 目录，在每次会话开始时：
1. 运行 `python .learning-profile/scripts/check-reviews.py`（如果当前环境只有 `python3`，则用 `python3`）。
2. 如果脚本输出到期复习项，第一句话提醒用户：
   "你有 {n} 个知识点需要复习：{list}。先花几分钟回顾一下？"
3. 如果脚本没有输出，不主动提及复习。
EOF
    CREATED+=("AGENTS.md review hint (appended)")
fi

# Always copy runtime helper scripts to profile (used by all platforms)
REPO_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROFILE_SCRIPTS="$PROFILE_DIR/scripts"
mkdir -p "$PROFILE_SCRIPTS"
for script_name in check-reviews.py record-review.py write-state.py migrate-profile.py; do
    REPO_SCRIPT="$REPO_SCRIPT_DIR/$script_name"
    cp "$REPO_SCRIPT" "$PROFILE_SCRIPTS/$script_name"
    chmod +x "$PROFILE_SCRIPTS/$script_name"
    CREATED+=("scripts/$script_name")
done

# Claude Code-specific: SessionStart hook config
CLAUDE_DIR="$LEARNING_DIR/.claude"
if [ -d "$CLAUDE_DIR" ]; then
    CLAUDE_SETTINGS="$CLAUDE_DIR/settings.json"
    if [ -f "$CLAUDE_SETTINGS" ]; then
        if ! grep -q "check-reviews" "$CLAUDE_SETTINGS" 2>/dev/null; then
            echo "  Note: Add Claude Code SessionStart hook (see references/automation/claude-code.md)"
        fi
    else
        echo "  Claude Code detected. See references/automation/claude-code.md for hook setup."
    fi
else
    echo "  No .claude/ directory — skipping Claude Code hook setup"
fi

if [ ${#CREATED[@]} -gt 0 ]; then
    echo "Learning profile initialized at $LEARNING_DIR"
    for f in "${CREATED[@]}"; do echo "  created: $f"; done
else
    echo "Learning profile already exists at $LEARNING_DIR (no files created)"
fi
echo "  courses/"
