#!/usr/bin/env pwsh
# Initialize .learning-profile directory for study.skill
# Usage: .\init-profile.ps1 [-Path <path>] (default: ~/learning)

param(
    [string]$Path = "$env:USERPROFILE\learning"
)

$profileDir = "$Path\.learning-profile"
$profileFile = "$profileDir\profile.json"
$coursesDir = "$profileDir\courses"

New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
New-Item -ItemType Directory -Force -Path $coursesDir | Out-Null
New-Item -ItemType Directory -Force -Path "$Path\courses" | Out-Null
$created = @()

# profile.json
if (-not (Test-Path -LiteralPath $profileFile)) {
    $now = (Get-Date).ToString("yyyy-MM-ddTHH:mm:sszzz")
    $profileJson = [ordered]@{
        schema_version = 2
        learner_id = "default"
        created_at = $now
        updated_at = $now
        preferences = [ordered]@{
            native_language = "zh"
            daily_time_budget_minutes = 30
            feedback_style = "normal"
            correction_mode = "inline"
            automation_declined = $false
            automation_declined_at = $null
        }
        learner_profile = [ordered]@{
            baseline = $null
            goals = @()
            known_languages = @()
            weak_prereqs = @()
            analogy_preferences = @()
            teaching_constraints = @()
            materials_summary = $null
            updated_at = $null
        }
    } | ConvertTo-Json -Depth 4
    [System.IO.File]::WriteAllText($profileFile, $profileJson + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
    $created += "profile.json"
} else {
    Write-Host "  profile.json already exists - skipped"
}

# AGENTS.md hint
$agentsFile = "$Path\AGENTS.md"
$hintMarker = "# [study.skill] review-check"
$agentsContent = if (Test-Path $agentsFile) { Get-Content $agentsFile -Raw } else { "" }
if ($agentsContent -and $agentsContent.Contains($hintMarker)) {
    Write-Host "  AGENTS.md review hint already present - skipped"
} else {
    $reviewHint = @(
        ""
        "# [study.skill] review-check"
        "# The following instructions are auto-generated by study.skill init script."
        ""
        "## Study assistant"
        "If .learning-profile/ exists in this workspace, on each session start:"
        "1. Run python .learning-profile/scripts/check-reviews.py. If only python3 exists, use python3."
        "2. If the script prints due review items, remind the user first and ask whether to review now."
        "3. If the script prints nothing, do not mention reviews."
    ) -join [Environment]::NewLine
    Add-Content -LiteralPath $agentsFile -Encoding UTF8 -Value $reviewHint
    $created += "AGENTS.md review hint (appended)"
}

# Always copy runtime helper scripts to profile (used by all platforms)
$profileScripts = "$profileDir\scripts"
New-Item -ItemType Directory -Force -Path $profileScripts | Out-Null
foreach ($scriptName in @("check-reviews.py", "record-review.py", "write-state.py", "migrate-profile.py")) {
    $repoScript = Join-Path $PSScriptRoot $scriptName
    Copy-Item $repoScript (Join-Path $profileScripts $scriptName) -Force
    $created += "scripts\$scriptName"
}

# Claude Code-specific: SessionStart hook config
$claudeDir = "$Path\.claude"
if (Test-Path $claudeDir) {
    Write-Host "  Claude Code detected. See references/automation/claude-code.md for hook setup."
} else {
    Write-Host "  No .claude/ directory - skipping Claude Code hook setup"
}

if ($created.Count -gt 0) {
    Write-Host "Learning profile initialized at $Path"
    foreach ($f in $created) { Write-Host "  created: $f" }
} else {
    Write-Host "Learning profile already exists at $Path (no files created)"
}
Write-Host "  courses\"
